services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
  server:
    image: server:latest
    container_name: server
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDRESS: "redis:6379"
      REDIS_PASSWORD: "secret"
    depends_on:
      - redis
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/v2202508293879372462.ultrasrv.de/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/v2202508293879372462.ultrasrv.de/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - server
