FROM golang:1.23-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -o main

FROM alpine:3.18
WORKDIR /app
RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && echo "America/Sao_Paulo" > /etc/timezone \
    && apk del tzdata
COPY --from=builder /build/main ./main
RUN mkdir /app/data
EXPOSE 8080
ENTRYPOINT ["./main"]