FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o main

FROM scratch
WORKDIR /app
COPY --from=builder /build/main ./main
EXPOSE 8080
ENTRYPOINT ["./main"]